#!/bin/bash

set -euo pipefail
set -x

artifactbundle='dollup.artifactbundle'
arch=$(uname -m)

mkdir -p ${artifactbundle}/${arch}
sed \
    -e "s/__VERSION__/${DEPLOY_VERSION}/g" \
    -e "s/__BINARY__/${arch}/g" \
    -e "s/__TRIPLE__/${arch}-unknown-linux-gnu/g" \
    Scripts/info.json > ${artifactbundle}/info.json

swift build -c release \
    --product dollup \
    --scratch-path .build.${arch} \
    --static-swift-stdlib

cp .build.${arch}/release/dollup ${artifactbundle}/${arch}/dollup
zip -r "${artifactbundle}.zip" "${artifactbundle}"
