#!/bin/bash

set -euo pipefail
set -x

while [[ $# -gt 0 ]]; do
    aws s3 cp $1 \
        "s3://tayloraswift/dollup/$DEPLOY_VERSION/$DEPLOY_PLATFORM-$(uname -m)/$1" \
        --content-type application/zip
    shift
done
