name: Deploy

permissions:
    contents: write
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version to deploy'
                required: true
                type: string
    workflow_call:
        inputs:
            version:
                description: 'The version to deploy'
                required: true
                type: string

jobs:
    macOS:
        runs-on: macos-26
        env:
            DEPLOY_VERSION: ${{ inputs.version }}
        steps:
            -   name: 🎀 Setup AWS CLI 🎀
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: 🎀 Checkout repository 🎀
                uses: actions/checkout@v6

            -   name: 🎀 Select Xcode 26.4 🎀
                run: sudo xcode-select -s /Applications/Xcode_26.4.app/Contents/Developer

            -   name: 🎀 Build Dollup 🎀
                run: Scripts/Build/macOS

            -   name: 🎀 Upload products 🎀
                run: Scripts/Deploy *.artifactbundle.zip
                env:
                    DEPLOY_PLATFORM: "${{ github.job }}"

    Linux:
        strategy:
            matrix:
                runner:
                    -   name: "Ubuntu (x86_64)"
                        id: ubuntu-24.04

                    -   name: "Ubuntu (aarch64)"
                        id: ubuntu-24.04-arm

        runs-on: ["${{ matrix.runner.id }}"]
        name: "${{ matrix.runner.name }}"
        env:
            DEPLOY_VERSION: ${{ inputs.version }}
        steps:
            -   name: 🎀 Setup AWS CLI 🎀
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: 🎀 Checkout repository 🎀
                uses: actions/checkout@v6

            -   name: 🎀 Install Swift 🎀
                uses: rarestype/swift-install-action@v1
                with:
                    swift-release: 6.3-RELEASE

            -   name: 🎀 Build Dollup 🎀
                run: Scripts/Build/Linux

            -   name: 🎀 Upload products 🎀
                run: Scripts/Deploy *.artifactbundle.zip
                env:
                    DEPLOY_PLATFORM: "${{ github.job }}"

    release:
        needs: [macOS, Linux]
        runs-on: macos-26
        name: Release
        env:
            DEPLOY_VERSION: ${{ inputs.version }}
        steps:
            -   name: 🎀 Checkout repository 🎀
                uses: actions/checkout@v6
                with:
                    repository: 'ordo-one/dollup'
                    token: ${{ secrets.ORDO_RELEASE_PAT }}
                    path: downstream

            -   name: 🎀 Generate Package.swift 🎀
                run: |
                    HOST="https://download.rarestype.com/dollup/$DEPLOY_VERSION"

                    BUNDLE_URL_LINUX_AARCH64="$HOST/Linux-aarch64/dollup.artifactbundle.zip"
                    BUNDLE_URL_LINUX_X86_64="$HOST/Linux-x86_64/dollup.artifactbundle.zip"
                    BUNDLE_URL_MACOS_ARM64="$HOST/macOS-arm64/dollup.artifactbundle.zip"

                    echo "macOS Bundle URL: ${BUNDLE_URL_MACOS_ARM64}"
                    echo "Linux Bundle URL (x86_64): ${BUNDLE_URL_LINUX_X86_64}"
                    echo "Linux Bundle URL (aarch64): ${BUNDLE_URL_LINUX_AARCH64}"

                    curl "$BUNDLE_URL_LINUX_AARCH64" -o Linux-aarch64.zip
                    curl "$BUNDLE_URL_LINUX_X86_64" -o Linux-x86_64.zip
                    curl "$BUNDLE_URL_MACOS_ARM64" -o macOS-arm64.zip

                    CHECKSUM_LINUX_AARCH64=$(swift package compute-checksum Linux-aarch64.zip)
                    CHECKSUM_LINUX_X86_64=$(swift package compute-checksum Linux-x86_64.zip)
                    CHECKSUM_MACOS_ARM64=$(swift package compute-checksum macOS-arm64.zip)

                    echo "macOS Checksum: ${CHECKSUM_MACOS_ARM64}"
                    echo "Linux Checksum (x86_64): ${CHECKSUM_LINUX_X86_64}"
                    echo "Linux Checksum (aarch64): ${CHECKSUM_LINUX_AARCH64}"

                    cd downstream

                    sed -e "s/__CHECKSUM_MACOS__/${CHECKSUM_MACOS_ARM64}/g" \
                        -e "s/__CHECKSUM_LINUX_X86_64__/${CHECKSUM_LINUX_X86_64}/g" \
                        -e "s/__CHECKSUM_LINUX_AARCH64__/${CHECKSUM_LINUX_AARCH64}/g" \
                        -e "s|__BUNDLE_URL_MACOS__|${BUNDLE_URL_MACOS_ARM64}|g" \
                        -e "s|__BUNDLE_URL_LINUX_X86_64__|${BUNDLE_URL_LINUX_X86_64}|g" \
                        -e "s|__BUNDLE_URL_LINUX_AARCH64__|${BUNDLE_URL_LINUX_AARCH64}|g" \
                        Package.template.swift > Package.swift

                    git config user.name "rarest automation"
                    git config user.email "automation@noreply.rarestype.com"

                    git add Package.swift
                    git commit -m "Release ${DEPLOY_VERSION}"
                    git tag "${DEPLOY_VERSION}"
                    git push origin master
                    git push origin refs/tags/${DEPLOY_VERSION}

            -   name: 🎀 Publish release 🎀
                uses: softprops/action-gh-release@v2
                with:
                    repository: 'ordo-one/dollup'
                    tag_name: ${{ github.ref_name }}
                    name: ${{ github.ref_name }}
                    token: ${{ secrets.ORDO_RELEASE_PAT }}

            -   name: 🎀 Update badge 🎀
                uses: rarestype/rarestbadge@v1
                if: always()
                with:
                    badge: SemanticRelease/_all
                    title: Release
